server:
  port: 8081

spring:
  application:
    name: auth-service

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:15m}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:7d}

cors:
  allowed-origins: http://localhost:3000
