server:
  port: 8081

spring:
  application:
    name: catalog-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,mappings,loggers
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus: DEBUG
    io.micrometer.prometheus: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
