server:
  port: 8084

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://order_service_db:5432/orderdb
    username: orderuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  jwt:
    secret:
    expiration-ms: 3600000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.jewelryshop.orderservice: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
